homepage:
    pattern:  /
    defaults: { _controller: FooAppsHelloBundle:Default:index }

hello:
    pattern:  /hello/{name}
    defaults: { _controller: FooAppsHelloBundle:Default:hello }
    requirements: { _method: get }

new_friend:
    pattern: /new
    defaults: { _controller: FooAppsHelloBundle:Friend:new }
    requirements: { _method: get }

create_friend:
    pattern: /new
    defaults: { _controller: FooAppsHelloBundle:Friend:create }
    requirements: { _method: post }
