friends:
    pattern:  /friends
    defaults: { _controller: FooAppsHelloBundle:Default:index }

hello:
    pattern:  /hello/{name}
    defaults: { _controller: FooAppsHelloBundle:Default:hello }
    requirements: { _method: get }

new_friend:
    pattern: /new
    defaults: { _controller: FooAppsHelloBundle:Friend:new }
    requirements: { _method: get|post }

edit_friend:
    pattern: /edit/{id}
    defaults: { _controller: FooAppsHelloBundle:Friend:edit }
    requirements: { _method: get|post }
